name: "Build CodeBerg Pages"
run-name: "Build CodeBerg Pages"

on:
  workflow_call:
  workflow_dispatch:
  push:
  #  branches-ignore: [main,master]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ forgejo.token }}

jobs:
  build:
    runs-on: codeberg-small-lazy
    steps:

      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y tidy pandoc git-extras

      - name: "Install templates"
        run: |
          mkdir -p ~/.pandoc/templates
          curl -sSL 'https://github.com/tajmone/pandoc-goodies/raw/refs/heads/master/templates/html5/github/GitHub.html5' -o ~/.pandoc/templates/GitHub.html5

      - name: "Retrieve Code of Conduct"
        run: curl --create-dirs --output code-of-conduct.md "${ENDPOINT}/CODE_OF_CONDUCT.md"
        env:
          ENDPOINTS: https://codeberg.org/norwd/.profile/raw/branch/main

      - name: "Retrieve Security Policy"
        run: curl --create-dirs --output security/policy.md "${ENDPOINT}/SECURITY.md"
        env:
          ENDPOINTS: https://codeberg.org/norwd/.profile/raw/branch/main

      - name: "Retrieve Contribution Guidlines"
        run: curl --output contributing.md "${ENDPOINT}/CONTRIBUTING.md"
        env:
          ENDPOINTS: https://codeberg.org/norwd/.profile/raw/branch/main

      - name: "Generate additional make configs for /quotes/{id} endpoints"
        run: jq --raw-output "${JQ_QUERY}" data/quotes.json | tee OID_ENDPOINTS.mk
        env:
          JQ_QUERY: '.[]._id["$oid"] | "OID_ENDPOINTS := $(OID_ENDPOINTS) \(.).json"'

      - name: "Generate additional make configs for /quotes/{author} endpoints"
        run: jq --raw-output "${JQ_QUERY}" data/quotes.json | tee AUTH_ENDPOINTS.mk
        env:
          JQ_QUERY: 'unique_by(.author)[] | "AUTH_ENDPOINTS := $(AUTH_ENDPOINTS) \( .author | gsub("\\(.+\\)$$"; "") | gsub("[^a-zA-Z]+"; "_") | gsub("_$$"; "") ).json"'

      - name: "Execute Makefile"
        timeout-minutes: 5
        run: make -j 16

      - name: "Tidy the HTML"
        run: find . -name '*.html' -not -path './.git*/*' -not -path './src*/*' | xargs tidy -indent --wrap 0 --output-html yes --warn-proprietary-attributes no -quiet -modify

      - name: "Exclude Files"
        run: rm -rf Makefile *.mk .nojekyll .git*/** src/**

      - name: "Deploy Pages"
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/quotes/
          token: ${{ forge.token }}
          source: .
