name: "Build CodeBerg Pages"
run-name: "Build CodeBerg Pages"

on:
  workflow_call:
  workflow_dispatch:
  push:
  #  branches-ignore: [main,master]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ forgejo.token }}

jobs:
  build:
    runs-on: codeberg-tiny
    steps:

      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y tidy pandoc git-extras

      - name: "Install templates"
        run: |
          mkdir -p ~/.pandoc/templates
          curl -sSL 'https://github.com/tajmone/pandoc-goodies/raw/refs/heads/master/templates/html5/github/GitHub.html5' -o ~/.pandoc/templates/GitHub.html5

      - name: "Execute Makefile"
        run: make

      #- name: "Tidy the HTML"
      #  run: find . -name '*.html' -not -path './.git*/*' -not -path './src*/*' | xargs tidy -indent --wrap 0 --output-html yes --warn-proprietary-attributes no -quiet -modify
