name: "Build CodeBerg Pages"
run-name: "Build CodeBerg Pages"

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '5 0 * * *'

permissions:
  contents: read

env:
  GH_TOKEN: ${{ forgejo.token }}
  BASE_URL: https://${{ forgejo.repository_owner }}.codeberg.page/quotes

jobs:
  build:
    runs-on: codeberg-small-lazy
    steps:

      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y tidy pandoc git-extras

      - name: "Install templates"
        run: curl -sSL --create-dirs --output ~/.pandoc/templates/GitHub.html5 "${ENDPOINT}"
        env:
          ENDPOINT: https://github.com/tajmone/pandoc-goodies/raw/refs/heads/master/templates/html5/github/GitHub.html5

      - name: "Execute Makefile"
        timeout-minutes: 5
        run: make -j 16

      - name: "Tidy the HTML"
        run: find . -name '*.html' -not -path './.git*/*' -not -path './src*/*' | xargs --verbose -IFILE tidy -indent --wrap 0 --output-html yes --warn-proprietary-attributes no -quiet -modify FILE

      - name: "Exclude Files"
        run: rm -rf Makefile *.mk .nojekyll .git*/** src/**

      - name: "Deploy Pages"
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: ${{ env.BASE_URL }}
          token: ${{ forgejo.token }}
          source: .
