name: "Build CodeBerg Pages"
run-name: "Build CodeBerg Pages"

on:
  workflow_call:
  workflow_dispatch:
  push:
  #  branches-ignore: [main,master]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ forgejo.token }}
  BASE_URL: https://${{ forgejo.repository_owner }}.codeberg.page/quotes

jobs:
  build:
    runs-on: codeberg-small-lazy
    steps:

      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y tidy pandoc git-extras

      - name: "Install templates"
        run: curl -sSL --create-dirs --output ~/.pandoc/templates/GitHub.html5 "${ENDPOINT}"
        env:
          ENDPOINT: https://github.com/tajmone/pandoc-goodies/raw/refs/heads/master/templates/html5/github/GitHub.html5

      - name: "Retrieve Code of Conduct"
        run: curl -sSL --create-dirs --output code-of-conduct.md "${ENDPOINT}"
        env:
          ENDPOINT: https://codeberg.org/norwd/.profile/raw/branch/main/CODE_OF_CONDUCT.md

      - name: "Retrieve Security Policy"
        run: curl -sSL --create-dirs --output security/policy.md "${ENDPOINT}"
        env:
          ENDPOINT: https://codeberg.org/norwd/.profile/raw/branch/main/SECURITY.md

      - name: "Retrieve Contribution Guidlines"
        run: curl -sSL --create-dirs --output contributing.md "${ENDPOINT}"
        env:
          ENDPOINT: https://codeberg.org/norwd/.profile/raw/branch/main/CONTRIBUTING.md

      - name: "Generate additional make configs for /quotes/{id} endpoints"
        run: jq --raw-output "${JQ_QUERY}" data/quotes.json | tee OID_ENDPOINTS.mk
        env:
          JQ_QUERY: '.[]._id["$oid"] | "OID_ENDPOINTS := $(OID_ENDPOINTS) \(.).json"'

      - name: "Generate additional make configs for /quotes/{author} endpoints"
        run: jq --raw-output "${JQ_QUERY}" data/quotes.json | tee AUTH_ENDPOINTS.mk
        env:
          JQ_QUERY: 'unique_by(.author)[] | "AUTH_ENDPOINTS := $(AUTH_ENDPOINTS) \( .author | gsub("\\(.+\\)$$"; "") | gsub("[^a-zA-Z]+"; "_") | gsub("_$$"; "") ).json"'

      - name: "Execute Makefile"
        timeout-minutes: 5
        run: make -j 16

      - name: "Tidy the HTML"
        run: find . -name '*.html' -not -path './.git*/*' -not -path './src*/*' | xargs tidy -indent --wrap 0 --output-html yes --warn-proprietary-attributes no -quiet -modify

      - name: "Exclude Files"
        run: rm -rf Makefile *.mk .nojekyll .git*/** src/**

      - name: "Generate a security.txt file"
        run: |
          tee security.txt << EOF
          Contact: ${BASE_URL}/contact
          Policy: ${BASE_URL}/security/policy
          Acknowledgments: ${BASE_URL}/humans
          Canonical: ${BASE_URL}/security.txt
          Expires: $(date -u +"%Y-12-31T23:59:59.999Z")
          EOF

      - name: "Generate a robots.txt file"
        run: |
          curl -sSL --create-dirs --output robots.txt https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt
          tee -a robots.txt << EOF

          Sitemap: ${BASE_URL}/sitemap.txt
          EOF

      - name: "Generate a version.txt file"
        run: |
          tee version.txt << EOF
          Deployed: $(date --universal +'%FT%TZ')
          Version: v0.1.${{ forgejo.run_number }}.$((${{ forgejo.run_attempt }} - 1))
          Source: ${{ forgejo.server_url }}/${{ forgejo.repository }}/tree/$(echo "${{ forgejo.sha }}" | head -c 7)
          EOF

      - name: "Generate a sitemap.txt file"
        run: |
          touch sitemap.txt # this ensures that the sitemap detects itself
          find . -type f -printf "${BASE_URL}/%P\n" | sed -e 's/\(\.html\)*$//g' | sort --unique | tee -a sitemap.txt

      - name: "Deploy Pages"
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: ${{ env.BASE_URL }}
          token: ${{ forgejo.token }}
          source: .
