name: "Build GitHub Pages"
run-name: "Build GitHub Pages"

on:
  workflow_call:
  push:
    branches-ignore: [main,master]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install tools"
        run: sudo apt install tidy pandoc

      - name: "Install templates"
        run: |
          mkdir -p ~/.pandoc/templates
          curl -sSL 'https://github.com/tajmone/pandoc-goodies/raw/refs/heads/master/templates/html5/github/GitHub.html5' -o ~/.pandoc/templates/GitHub.html5

      - name: "Retrieve Code of Conduct"
        run: curl --header "${MEDIA_TYPE_HEADER}" --header "${AUTH_TOKEN_HEADER}" --create-dirs --output code-of-conduct.md "${CONTENTS_ENDPOINT}/CODE_OF_CONDUCT.md"
        env:
          CONTENTS_ENDPOINT: '${{ github.api_url }}/repos/${{ github.repository_owner }}/.github/contents'
          MEDIA_TYPE_HEADER: "Accept: application/vnd.github.raw"
          AUTH_TOKEN_HEADER: "Authorization: Bearer ${{ github.token }}"

      - name: "Retrieve Security Policy"
        run: curl --header "${MEDIA_TYPE_HEADER}" --header "${AUTH_TOKEN_HEADER}" --create-dirs --output security/policy.md "${CONTENTS_ENDPOINT}/SECURITY.md"
        env:
          CONTENTS_ENDPOINT: '${{ github.api_url }}/repos/${{ github.repository_owner }}/.github/contents'
          MEDIA_TYPE_HEADER: "Accept: application/vnd.github.raw"
          AUTH_TOKEN_HEADER: "Authorization: Bearer ${{ github.token }}"

      - name: "Retrieve Contribution Guidlines"
        run: curl --header "${MEDIA_TYPE_HEADER}" --header "${AUTH_TOKEN_HEADER}" --create-dirs --output contributing.md "${CONTENTS_ENDPOINT}/CONTRIBUTING.md"
        env:
          CONTENTS_ENDPOINT: '${{ github.api_url }}/repos/${{ github.repository_owner }}/.github/contents'
          MEDIA_TYPE_HEADER: "Accept: application/vnd.github.raw"
          AUTH_TOKEN_HEADER: "Authorization: Bearer ${{ github.token }}"

      - id: latest-release
        name: "Get Details of Latest Release"
        run: gh release view --json "${JQ_PROPS}" --jq "${JQ_QUERY}" | tee -a "${GITHUB_OUTPUT}"
        env:
          GH_REPO: '${{ github.repository }}'
          JQ_PROPS: 'tagName'
          JQ_QUERY: '"tag_name=" + (.tagName | tostring)'

      - name: "Generate an authors.yaml file"
        run: gh api "${ENDPOINT}" --jq "${JQ_QUERY}" | tee authors.yaml
        env:
          ENDPOINT: '/repos/${{ github.repository }}/contributors'
          JQ_QUERY: '"author-meta:" + (["", (.[] | .login)] | join("\n- "))'

      - name: "Generate a changelog.md file"
        run: gh api "${ENDPOINT}" --template "${TEMPLATE}" | tee changelog.md
        env:
          ENDPOINT: '/repos/${{ github.repository }}/releases'
          TEMPLATE: |
            ---
            lang: en
            title: Changelog
            ...

            {{ range . -}}

            ## [{{.name}}]({{ .html_url }})

            {{- if .draft -}}
            {{ " " }}![This is a draft release.](https://img.shields.io/badge/DRAFT-grey)
            {{- else if .prerelease -}}
            {{ " " }}![This is a pre-release.](https://img.shields.io/badge/PRE--RELEASE-orange)
            {{- else if eq .tag_name "${{ steps.latest-release.outputs.tag_name }}" -}}
            {{ " " }}![This is the latest release.](https://img.shields.io/badge/LATEST-green)
            {{- end }}

            {{ .body }}

            {{ if .assets -}}

            ### Asset Downloads

            {{- "\n" -}}

            {{ range .assets }}
            - [{{ or .label .name }}]({{ .browser_download_url }})
            {{- end }}

            {{ end }}

            {{- end }}

            {{- /* noop */ -}}

      - name: "Generate a humans.md file"
        run: gh api "${ENDPOINT}" --template "${TEMPLATE}" | sh | tee humans.md
        env:
          ENDPOINT: '/repos/${{ github.repository }}/contributors'
          TEMPLATE: |
            echo "# Humans to Thank"
            echo
            echo "A huge thanks to all and colaborators who have contributed on GitHub!"
            echo
            echo "## Contributors to [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})"
            echo
            {{range .}}
            gh api '/users/{{ .login }}' --jq '"- " + (.name // .login) + " aka [@" + .login + "](" + .html_url + ")"'
            {{end}}

      - name: "Create endpoint `/{lang}.json`"
        run: curl -sSL "${ENDPOINT}" | python -c "${CSV2JSON}" | jq --raw-output "${JQ_QUERY}" | xargs -ILANG sh -c "${COPY_CMD}"
        env:
          ENDPOINT: 'https://github.com/datasets/language-codes/raw/refs/heads/main/data/language-codes.csv'
          JQ_QUERY: '.[].alpha2'
          COPY_CMD: 'cp data/quotes-LANG.json LANG.json || cp data/quotes.json LANG.json'
          CSV2JSON: |
            import csv
            import sys
            import json

            objects = []
            reader = csv.DictReader(sys.stdin)
            for row in reader:
                obj = dict(row)
                objects.append(obj)

            arr = json.dumps(objects)
            print(arr)

      - name: "Execute Makefile"
        run: |
          make -f - << \EOF

          PANDOC_FORMAT := markdown+yaml_metadata_block+backtick_code_blocks+fenced_code_attributes+inline_notes+emoji-implicit_figures+shortcut_reference_links+spaced_reference_links+autolink_bare_uris-citations
          ENDPOINTS := qotd.json random.json

          all: all_json all_html all_txt
          	rm -f header.*

          all_json: $(ENDPOINTS) $(ENDPOINTS:.json=.txt)
          	@echo Generated $^

          all_html: $(patsubst %.md,%.html,$(wildcard *.md */*.md */*/*.md))
          	@echo Generated $^

          all_txt: $(patsubst %.html,%.txt,$(wildcard *.html */*.html */*/*.html))
          	@echo Generated $^

          index.md: README.md
          	@echo Generating $@...
          	cp $< $@

          qotd.md: qotd.json
          	@echo Generating $@...
          	jq --raw-output '"> \(.text)\n\n- \(.author)"' $< | tee $@

          qotd.json: data/quotes.json
          	@echo Generating $@...
          	jq --raw-output '.[] | { text: .text, author: .author } | tostring' $< | sort --random-sort | tail --lines 1 | jq | tee $@

          random.md: qotd.md
          	@echo Generating $@...
          	cp $< $@

          random.json: qotd.json
          	@echo Generating $@...
          	cp $< $@

          %.html: %.md
          	@echo Generating $@...
          	pandoc --quiet --standalone --template=GitHub.html5 --metadata-file=authors.yaml --include-in-header=header.html --from $(PANDOC_FORMAT) --to html --output $@ $<

          %.txt: %.html
          	@echo Generating $@...
          	pandoc --from html --to plain --wrap=none $< --output $@

          .PHONY: all all_json all_html all_txt

          EOF

      - name: "Tidy the HTML"
        run: find . -name '*.html' | xargs tidy -indent --wrap 0 --output-html yes --warn-proprietary-attributes no -quiet -modify

      - name: "Archive Pages Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: |
            .
            !CNAME
            !.nojekyll
            !.git*/**
